"""Garante que migrations/versions/ representa fielmente o schema atual de
app.models — roda alembic upgrade head num banco descartável e usa
`alembic check` (Alembic 1.9+) pra detectar drift entre os models e a
última migration. Se este teste falhar, alguém mudou um model sem gerar a
migration correspondente: rode `alembic revision --autogenerate -m "..."`
e commite o arquivo novo em migrations/versions/ (ver docs/MIGRACOES.md).

Existir esse teste dentro da MESMA suíte que já roda em todo PR/push (ver
.github/workflows/backend-ci.yml) é o que faz esse gate valer de verdade
pra CI/CD — sem precisar de nenhuma ferramenta nova, só reaproveitando o
pytest que já é o portão de qualidade do projeto."""

from pathlib import Path

from alembic import command
from alembic.config import Config

BACKEND_ROOT = Path(__file__).resolve().parent.parent
ALEMBIC_INI = BACKEND_ROOT / "alembic.ini"


def test_migrations_head_matches_models(monkeypatch, tmp_path):
    from app.core.config import settings

    scratch_db = tmp_path / "migrations_check.db"
    monkeypatch.setattr(settings, "DATABASE_URL", f"sqlite:///{scratch_db}")

    cfg = Config(str(ALEMBIC_INI))
    command.upgrade(cfg, "head")
    # Levanta alembic.util.exc.AutogenerateDiffsDetected se o schema dos
    # models divergir da última migration aplicada.
    command.check(cfg)


def test_migration_corrige_tipo_jogador_id_legado(monkeypatch, tmp_path):
    """Regressão: a migration baseline (a5f913d8cd90) já cria
    `jogadortorneiolink` com `regra_extra_id` (o rename de `tipo_jogador_id`
    — ver docs/REGRA_EXTRA.md — aconteceu num edit direto do model, ANTES do
    Alembic existir no projeto), então ela nunca testava o caminho de um
    banco que já existia antes dessa rodada, com a coluna antiga de
    verdade. A migration f0256c9944ef existe só pra cobrir esse caso — este
    teste simula um banco "legado" (upgrade até antes do fix, coluna
    renomeada manualmente de volta pro nome antigo) e confirma que
    `alembic upgrade head` conserta e `alembic check` não acusa divergência
    depois."""
    import sqlalchemy as sa
    from app.core.config import settings

    scratch_db = tmp_path / "migrations_legacy_check.db"
    monkeypatch.setattr(settings, "DATABASE_URL", f"sqlite:///{scratch_db}")

    cfg = Config(str(ALEMBIC_INI))
    command.upgrade(cfg, "28947b4e7a24")  # head anterior ao fix

    engine = sa.create_engine(f"sqlite:///{scratch_db}")
    with engine.begin() as conn:
        conn.execute(sa.text(
            "ALTER TABLE jogadortorneiolink RENAME COLUMN regra_extra_id TO tipo_jogador_id"
        ))

    command.upgrade(cfg, "head")

    with engine.begin() as conn:
        colunas = {row[1] for row in conn.execute(sa.text("PRAGMA table_info(jogadortorneiolink)"))}
    assert "regra_extra_id" in colunas
    assert "tipo_jogador_id" not in colunas

    command.check(cfg)


def test_migration_corrige_coluna_tipo_ausente(monkeypatch, tmp_path):
    """Regressão: `ba9d81184506` cria a tabela `pontuacaoextra` (nova) e
    adiciona a coluna `tipo` em `jogadortorneiolink` (tabela já existente) na
    MESMA migration. `create_all()` só cria tabelas que faltam, nunca altera
    uma tabela existente — então um banco de produção onde `pontuacaoextra`
    já foi criada por `create_all` (antes do Alembic existir), mas
    `jogadortorneiolink.tipo` nunca chegou a ser adicionada, é exatamente o
    tipo de banco que precisa ser adotado stampando pra `ba9d81184506` (pra
    não tentar recriar `pontuacaoextra`) sem ter rodado o `add_column` de
    verdade. A migration 6944ed7a020e existe só pra cobrir esse caso — este
    teste simula esse banco (upgrade até a baseline, cria `pontuacaoextra` na
    mão espelhando o model, stampa `ba9d81184506` sem rodar seu upgrade()) e
    confirma que `alembic upgrade head` adiciona a coluna que faltava e
    `alembic check` não acusa divergência depois."""
    import sqlalchemy as sa
    from app.core.config import settings
    from app.models import PontuacaoExtra

    scratch_db = tmp_path / "migrations_tipo_ausente_check.db"
    monkeypatch.setattr(settings, "DATABASE_URL", f"sqlite:///{scratch_db}")

    cfg = Config(str(ALEMBIC_INI))
    command.upgrade(cfg, "a5f913d8cd90")  # só a baseline

    engine = sa.create_engine(f"sqlite:///{scratch_db}")
    # Simula create_all() criando a tabela nova (pontuacaoextra existe, mas
    # jogadortorneiolink.tipo nunca foi adicionada).
    PontuacaoExtra.__table__.create(bind=engine)
    command.stamp(cfg, "ba9d81184506")  # marca como aplicada sem rodar upgrade()

    command.upgrade(cfg, "head")

    with engine.begin() as conn:
        colunas = {row[1] for row in conn.execute(sa.text("PRAGMA table_info(jogadortorneiolink)"))}
    assert "tipo" in colunas

    command.check(cfg)
