"""jogador_data_nascimento_vira_date

Revision ID: 8a982e5232ab
Revises: 9179338bd373
Create Date: 2026-07-12 11:05:41.915383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a982e5232ab'
down_revision: Union[str, Sequence[str], None] = '9179338bd373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
