"""administrador

Revision ID: 4e33254b70b5
Revises: dc2c2309d6cd
Create Date: 2026-07-11 16:04:01.834070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e33254b70b5'
down_revision: Union[str, Sequence[str], None] = 'dc2c2309d6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # Lojas que já existiam antes desta coluna já estavam operando
    # normalmente — não faz sentido bloqueá-las retroativamente.
    # server_default='APROVADA' faz esse grandfathering; o default Python de
    # `Loja.status` (PENDENTE) só vale pra cadastros novos a partir de agora.
    #
    # No Postgres, add_column não cria o tipo ENUM nativo sozinho (só
    # create_table faz isso) — sem este .create() explícito o ALTER TABLE
    # falha com "type statusaprovacaoloja does not exist".
    status_loja_enum = sa.Enum('PENDENTE', 'APROVADA', 'REJEITADA', name='statusaprovacaoloja')
    status_loja_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'status',
            status_loja_enum,
            nullable=True,
            server_default='APROVADA',
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.drop_column('status')

    sa.Enum(name='statusaprovacaoloja').drop(op.get_bind(), checkfirst=True)

    op.drop_table('administrador')
    # ### end Alembic commands ###
