"""torneio conta em eventos

Revision ID: dc2c2309d6cd
Revises: 1773ca531cca
Create Date: 2026-07-11 15:48:28.285396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc2c2309d6cd'
down_revision: Union[str, Sequence[str], None] = '1773ca531cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default explícito: sem ele, adicionar uma coluna NOT NULL numa
    # tabela que já tem linhas falha tanto em SQLite quanto em Postgres.
    # Linhas existentes passam a contar em eventos por padrão, igual a
    # qualquer torneio novo.
    with op.batch_alter_table('torneio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_em_eventos', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneio', schema=None) as batch_op:
        batch_op.drop_column('conta_em_eventos')

    # ### end Alembic commands ###
