"""torneio_data_planejada_vira_date

Revision ID: 9179338bd373
Revises: 524495366f3d
Create Date: 2026-07-12 09:59:20.475140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9179338bd373'
down_revision: Union[str, Sequence[str], None] = '524495366f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneio', schema=None) as batch_op:
        batch_op.alter_column('data_planejada',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneio', schema=None) as batch_op:
        batch_op.alter_column('data_planejada',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
