"""baseline: schema atual (pre Alembic)

Revision ID: a5f913d8cd90
Revises: 
Create Date: 2026-07-08 00:33:06.626512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5f913d8cd90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogoatualizacao',
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tcg')
    )
    op.create_table('composicaopartida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conquista',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sa.Enum('HORAS_JOGADAS', 'TORNEIOS_JOGADOS', 'VITORIAS', 'COMPOSICOES_JOGADAS', 'SEQUENCIA_VITORIAS', 'PODIOS', name='categoriaconquista'), nullable=False),
    sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conquista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conquista_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_conquista_codigo'), ['codigo'], unique=True)

    op.create_table('representacaocomposicao',
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('representacaocomposicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_representacaocomposicao_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_representacaocomposicao_tcg'), ['tcg'], unique=False)

    op.create_table('unidadecatalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tcg', 'external_id', name='unidade_catalogo_unique')
    )
    with op.batch_alter_table('unidadecatalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidadecatalogo_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidadecatalogo_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidadecatalogo_tcg'), ['tcg'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foto')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_senha'), ['senha'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_tipo'), ['tipo'], unique=False)

    op.create_table('composicaopartidaunidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composicao_partida_id', sa.Integer(), nullable=False),
    sa.Column('unidade_catalogo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composicao_partida_id'], ['composicaopartida.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_catalogo_id'], ['unidadecatalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conquistanivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('nome_nivel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conquista_id', 'nivel', name='conquista_nivel_unique')
    )
    op.create_table('jogador',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loja',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banner'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loja_nome'), ['nome'], unique=False)

    op.create_table('representacaocomposicaounidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representacao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('unidade_catalogo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['representacao_id'], ['representacaocomposicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_catalogo_id'], ['unidadecatalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicoconquista',
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('progresso_no_momento', sa.Float(), nullable=False),
    sa.Column('conquistado_em', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquista.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jogador_id', 'conquista_id', 'nivel', name='historico_conquista_unique')
    )
    op.create_table('jogadorconquista',
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('progresso_atual', sa.Float(), nullable=False),
    sa.Column('nivel_atual', sa.Integer(), nullable=False),
    sa.Column('nivel_atual_em', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquista.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jogador_id', 'conquista_id', name='jogador_conquista_unique')
    )
    op.create_table('jogadorcriado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.Column('apelido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'tcg', name='jogador_criado_game_id_tcg_unique'),
    sa.UniqueConstraint('jogador_id', 'tcg', name='jogador_criado_jogador_tcg_unique')
    )
    op.create_table('lojajogadorlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('creditos', sa.Float(), nullable=False),
    sa.Column('apelido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'jogador_id', name='loja_id_jogador_id_unique')
    )
    op.create_table('temporada',
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ano_inicio', sa.Integer(), nullable=False),
    sa.Column('mes_inicio', sa.Integer(), nullable=False),
    sa.Column('ano_fim', sa.Integer(), nullable=False),
    sa.Column('mes_fim', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipojogador',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pt_vitoria', sa.Float(), nullable=False),
    sa.Column('pt_derrota', sa.Float(), nullable=False),
    sa.Column('pt_empate', sa.Float(), nullable=False),
    sa.Column('pt_oponente_perde', sa.Float(), nullable=False),
    sa.Column('pt_oponente_ganha', sa.Float(), nullable=False),
    sa.Column('pt_oponente_empate', sa.Float(), nullable=False),
    sa.Column('tcg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicocredito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('valor_antigo', sa.Float(), nullable=True),
    sa.Column('valor_novo', sa.Float(), nullable=True),
    sa.Column('tipo', sa.Enum('ADICAO', 'REMOCAO', 'COMPRA', 'CADASTRO', name='tipomovimentacaocredito'), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('min_quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lojajogadororganizadortcg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_jogador_link_id', sa.Integer(), nullable=False),
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.ForeignKeyConstraint(['loja_jogador_link_id'], ['lojajogadorlink.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_jogador_link_id', 'tcg', name='unique_organizador_tcg')
    )
    op.create_table('torneio',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tempo_por_rodada', sa.Integer(), nullable=False),
    sa.Column('data_planejada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('hora_planejada', sa.Time(), nullable=True),
    sa.Column('formato', sa.Enum('PADRAO', 'GLC', 'DRAFT', name='formatotorneio'), nullable=True),
    sa.Column('melhor_de', sa.Enum('MD1', 'MD3', 'MD5', name='formatomd'), nullable=False),
    sa.Column('jogo', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.Column('tipo', sa.Enum('IMPORTADO', 'CRIADO', name='tipotorneio'), nullable=False),
    sa.Column('taxa', sa.Float(), nullable=False),
    sa.Column('premio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('n_rodadas', sa.Integer(), nullable=False),
    sa.Column('rodada_atual', sa.Integer(), nullable=False),
    sa.Column('regra_basica_id', sa.Integer(), nullable=True),
    sa.Column('pontuacao_de_participacao', sa.Integer(), nullable=False),
    sa.Column('inicio_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fim_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANDAMENTO', 'FINALIZADO', name='statustorneio'), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.ForeignKeyConstraint(['regra_basica_id'], ['tipojogador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('torneio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_torneio_cidade'), ['cidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_torneio_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_torneio_tempo_por_rodada'), ['tempo_por_rodada'], unique=False)

    op.create_table('historicoitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'VENDA', 'REPOSICAO', 'ALTERACAO', 'CADASTRO', 'REMOCAO', name='tipomovimentacaoitem'), nullable=False),
    sa.Column('campo_alterado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_antigo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_novo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemtransacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('nome_item', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogadortorneiolink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_criado_id', sa.Integer(), nullable=False),
    sa.Column('regra_extra_id', sa.Integer(), nullable=True),
    sa.Column('pontuacao', sa.Float(), nullable=False),
    sa.Column('pontuacao_com_regras', sa.Float(), nullable=False),
    sa.Column('apelido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composicao_representacao_id', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=False),
    sa.Column('derrotas', sa.Integer(), nullable=False),
    sa.Column('empates', sa.Integer(), nullable=False),
    sa.Column('byes', sa.Integer(), nullable=False),
    sa.Column('porcentagem_vitorias_oponentes', sa.Float(), nullable=True),
    sa.Column('porcentagem_vitorias_oponentes_oponentes', sa.Float(), nullable=True),
    sa.Column('torneio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['composicao_representacao_id'], ['representacaocomposicao.id'], ),
    sa.ForeignKeyConstraint(['jogador_criado_id'], ['jogadorcriado.id'], ),
    sa.ForeignKeyConstraint(['regra_extra_id'], ['tipojogador.id'], ),
    sa.ForeignKeyConstraint(['torneio_id'], ['torneio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogadorcomposicaounidade',
    sa.Column('unidade_catalogo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_torneio_link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jogador_torneio_link_id'], ['jogadortorneiolink.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_catalogo_id'], ['unidadecatalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rodada',
    sa.Column('jogador1_id', sa.Integer(), nullable=True),
    sa.Column('jogador2_id', sa.Integer(), nullable=True),
    sa.Column('vencedor_id', sa.Integer(), nullable=True),
    sa.Column('num_rodada', sa.Integer(), nullable=False),
    sa.Column('mesa', sa.Integer(), nullable=True),
    sa.Column('data_de_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizada', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['jogador1_id'], ['jogadortorneiolink.id'], ),
    sa.ForeignKeyConstraint(['jogador2_id'], ['jogadortorneiolink.id'], ),
    sa.ForeignKeyConstraint(['torneio_id'], ['torneio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vencedor_id'], ['jogadortorneiolink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rodadacomposicao',
    sa.Column('rodada_id', sa.Integer(), nullable=False),
    sa.Column('jogador_torneio_link_id', sa.Integer(), nullable=False),
    sa.Column('composicao_partida_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composicao_partida_id'], ['composicaopartida.id'], ),
    sa.ForeignKeyConstraint(['jogador_torneio_link_id'], ['jogadortorneiolink.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodada.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rodada_id', 'jogador_torneio_link_id', name='rodada_composicao_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rodadacomposicao')
    op.drop_table('rodada')
    op.drop_table('jogadorcomposicaounidade')
    op.drop_table('jogadortorneiolink')
    op.drop_table('itemtransacao')
    op.drop_table('historicoitem')
    with op.batch_alter_table('torneio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_torneio_tempo_por_rodada'))
        batch_op.drop_index(batch_op.f('ix_torneio_estado'))
        batch_op.drop_index(batch_op.f('ix_torneio_cidade'))

    op.drop_table('torneio')
    op.drop_table('lojajogadororganizadortcg')
    op.drop_table('item')
    op.drop_table('historicocredito')
    op.drop_table('transacao')
    op.drop_table('tipojogador')
    op.drop_table('temporada')
    op.drop_table('lojajogadorlink')
    op.drop_table('jogadorcriado')
    op.drop_table('jogadorconquista')
    op.drop_table('historicoconquista')
    op.drop_table('categoria')
    op.drop_table('representacaocomposicaounidade')
    with op.batch_alter_table('loja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loja_nome'))

    op.drop_table('loja')
    op.drop_table('jogador')
    op.drop_table('conquistanivel')
    op.drop_table('composicaopartidaunidade')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_tipo'))
        batch_op.drop_index(batch_op.f('ix_usuario_senha'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('unidadecatalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidadecatalogo_tcg'))
        batch_op.drop_index(batch_op.f('ix_unidadecatalogo_nome'))
        batch_op.drop_index(batch_op.f('ix_unidadecatalogo_external_id'))

    op.drop_table('unidadecatalogo')
    with op.batch_alter_table('representacaocomposicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_representacaocomposicao_tcg'))
        batch_op.drop_index(batch_op.f('ix_representacaocomposicao_nome'))

    op.drop_table('representacaocomposicao')
    with op.batch_alter_table('conquista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conquista_codigo'))
        batch_op.drop_index(batch_op.f('ix_conquista_categoria'))

    op.drop_table('conquista')
    op.drop_table('composicaopartida')
    op.drop_table('catalogoatualizacao')
    # ### end Alembic commands ###
