"""pontuacao extra: tipo em jogadortorneiolink + tabela pontuacaoextra

Revision ID: ba9d81184506
Revises: a5f913d8cd90
Create Date: 2026-07-08 00:39:45.604784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba9d81184506'
down_revision: Union[str, Sequence[str], None] = 'a5f913d8cd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontuacaoextra',
    sa.Column('jogador_criado_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Enum('NOVATO', 'JUIZ', 'OUTROS', name='motivopontuacaoextra'), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jogador_criado_id'], ['jogadorcriado.id'], ),
    sa.ForeignKeyConstraint(['torneio_id'], ['torneio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default garante que linhas já existentes (produção com dados
    # reais) recebam 'JOGADOR' automaticamente — sem isso, adicionar uma
    # coluna NOT NULL numa tabela não-vazia falha tanto em SQLite quanto em
    # Postgres. O default fica no schema (não só no lado do Python) de
    # propósito, então mesmo um INSERT feito fora da aplicação continua
    # respeitando o mesmo valor padrão.
    with op.batch_alter_table('jogadortorneiolink', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'tipo',
            sa.Enum('JOGADOR', 'JUIZ', name='tipoparticipantetorneio'),
            nullable=False,
            server_default='JOGADOR',
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadortorneiolink', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    op.drop_table('pontuacaoextra')
    # ### end Alembic commands ###
