"""eventos: metas, regras, participantes, pontos manuais

Revision ID: 28947b4e7a24
Revises: ba9d81184506
Create Date: 2026-07-08 17:27:35.737661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28947b4e7a24'
down_revision: Union[str, Sequence[str], None] = 'ba9d81184506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('tcg', sa.Enum('POKEMON', 'ONEPIECE', 'POKEMON_VGC', 'POKEMON_GO', name='tcg'), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metaevento',
    sa.Column('pontos_necessarios', sa.Integer(), nullable=False),
    sa.Column('recompensa_descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recompensa_imagem_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participanteevento',
    sa.Column('jogador_criado_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jogador_criado_id'], ['jogadorcriado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'jogador_criado_id', name='evento_id_jogador_criado_id_unique')
    )
    op.create_table('pontosmanualevento',
    sa.Column('jogador_criado_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jogador_criado_id'], ['jogadorcriado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regrapontuacaoevento',
    sa.Column('tipo', sa.Enum('VITORIA', 'DERROTA', 'EMPATE', 'PARTICIPACAO', name='tiporegrapontuacaoevento'), nullable=False),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regrapontuacaoevento')
    op.drop_table('pontosmanualevento')
    op.drop_table('participanteevento')
    op.drop_table('metaevento')
    op.drop_table('evento')
    # ### end Alembic commands ###
