"""jogador_torneio_link_unique_tipo

Revision ID: 524495366f3d
Revises: 4e33254b70b5
Create Date: 2026-07-11 23:38:04.208858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '524495366f3d'
down_revision: Union[str, Sequence[str], None] = '4e33254b70b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadortorneiolink', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_jogador_torneio_tipo', ['jogador_criado_id', 'torneio_id', 'tipo'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadortorneiolink', schema=None) as batch_op:
        batch_op.drop_constraint('uix_jogador_torneio_tipo', type_='unique')

    # ### end Alembic commands ###
