"""jogador_torneio_link_role_unificado

Revision ID: 75d688648a4b
Revises: 8a982e5232ab
Create Date: 2026-07-12 15:40:33.995852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75d688648a4b'
down_revision: Union[str, Sequence[str], None] = '8a982e5232ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    if conn.dialect.name == "postgresql":
        # Enum nativo do Postgres não aceita novo valor via ALTER COLUMN
        # TYPE (isso é um no-op silencioso quando o nome do tipo não muda) —
        # precisa de ALTER TYPE ... ADD VALUE, que por sua vez não pode ser
        # usado (no UPDATE logo abaixo) na MESMA transação em que foi
        # adicionado. autocommit_block roda esse ALTER TYPE fora da
        # transação da migration, comitando na hora, pra liberar o uso do
        # valor novo já no data-merge seguinte. SQLite não tem esse
        # conceito (enum lá é só VARCHAR+CHECK, o alter_column no fim desta
        # função já recria o CHECK com o valor novo).
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE tipoparticipantetorneio ADD VALUE IF NOT EXISTS 'JOGADOR_E_JUIZ'")

    # Antes de apertar a constraint pra "1 linha por jogador por torneio",
    # funde eventuais pares (jogador_criado_id, torneio_id) com 2 linhas — o
    # esquema anterior (uma linha por papel), agora abandonado em favor de
    # JOGADOR_E_JUIZ. Mantém a linha de JOGADOR (é ela que carrega
    # vitórias/derrotas/composição de verdade), soma a pontuação da(s)
    # outra(s) linha(s) nela e descarta o resto.
    duplicados = conn.execute(sa.text(
        "SELECT jogador_criado_id, torneio_id FROM jogadortorneiolink "
        "GROUP BY jogador_criado_id, torneio_id HAVING COUNT(*) > 1"
    )).fetchall()

    for jogador_criado_id, torneio_id in duplicados:
        linhas = conn.execute(sa.text(
            "SELECT id, tipo, pontuacao, pontuacao_com_regras FROM jogadortorneiolink "
            "WHERE jogador_criado_id = :jcid AND torneio_id = :tid"
        ), {"jcid": jogador_criado_id, "tid": torneio_id}).fetchall()

        linha_principal = next((l for l in linhas if l.tipo == "JOGADOR"), linhas[0])
        outras = [l for l in linhas if l.id != linha_principal.id]

        pontuacao_total = linha_principal.pontuacao + sum(l.pontuacao for l in outras)
        pontuacao_com_regras_total = linha_principal.pontuacao_com_regras + sum(l.pontuacao_com_regras for l in outras)

        conn.execute(sa.text(
            "UPDATE jogadortorneiolink SET tipo = 'JOGADOR_E_JUIZ', pontuacao = :p, "
            "pontuacao_com_regras = :pcr WHERE id = :id"
        ), {"p": pontuacao_total, "pcr": pontuacao_com_regras_total, "id": linha_principal.id})

        for outra in outras:
            conn.execute(sa.text("DELETE FROM jogadortorneiolink WHERE id = :id"), {"id": outra.id})

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadortorneiolink', schema=None) as batch_op:
        if conn.dialect.name != "postgresql":
            # No Postgres o tipo (mesmo nome, tipoparticipantetorneio) já
            # foi alargado acima via ALTER TYPE — refazer isso aqui via
            # alter_column seria um no-op (SQLAlchemy não emite DDL quando o
            # nome do enum não muda) e é desnecessário.
            batch_op.alter_column('tipo',
                   existing_type=sa.VARCHAR(length=7),
                   type_=sa.Enum('JOGADOR', 'JUIZ', 'JOGADOR_E_JUIZ', name='tipoparticipantetorneio'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'JOGADOR'"))
        batch_op.drop_constraint(batch_op.f('uix_jogador_torneio_tipo'), type_='unique')
        batch_op.create_unique_constraint('uix_jogador_torneio', ['jogador_criado_id', 'torneio_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        # Postgres não suporta remover um valor de um enum nativo (só
        # recriando o tipo do zero) — e linhas já existentes podem estar
        # com tipo='JOGADOR_E_JUIZ' de verdade, então não há downgrade
        # seguro e automático aqui.
        raise NotImplementedError(
            "Downgrade desta migration não é suportado em Postgres: remover "
            "'JOGADOR_E_JUIZ' de um enum nativo exige recriar o tipo manualmente."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadortorneiolink', schema=None) as batch_op:
        batch_op.drop_constraint('uix_jogador_torneio', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_jogador_torneio_tipo'), ['jogador_criado_id', 'torneio_id', 'tipo'])
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('JOGADOR', 'JUIZ', 'JOGADOR_E_JUIZ', name='tipoparticipantetorneio'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'JOGADOR'"))

    # ### end Alembic commands ###
